# Generated by Django 4.2.2 on 2023-06-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=40)),
                ('director', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image', models.TextField()),
                ('ratings', models.IntegerField()),
            ],
        ),
    ]
